export const stylesObject = {
  circle: {
    withCamera: {
      width: '3.4375rem',
      height: '3.4375rem',
      borderRadius: '50%',
      fontSize: 'var(--ds-font-size-11)',
      fontWeight: 'bold',
      border: 'var(--ds-borders-1) solid var(--ds-grayscale-80)',
      lineHeight: '3.4375rem',
    },
    regular: {
      width: '1rem',
      height: '1rem',
      borderRadius: '50%',
      fontSize: 'var(--ds-font-size-2)',
      lineHeight: '1rem',
    },
    large: {
      width: '1.375rem',
      height: '1.375rem',
      borderRadius: '50%',
      fontSize: 'var(--ds-font-size-3)',
      lineHeight: '1.375rem',
    },
    xlarge: {
      width: '1.875rem',
      height: '1.875rem',
      borderRadius: '50%',
      fontSize: 'var(--ds-font-size-4)',
      lineHeight: '1.875rem',
    },
  },
  square: {
    withCamera: {
      width: '3.4375rem',
      height: '3.4375rem',
      borderRadius: 'var(--ds-corner-radius-5)',
      fontSize: 'var(--ds-font-size-11)',
      fontWeight: 'bold',
      border: 'var(--ds-borders-1) solid var(--ds-grayscale-80)',
      lineHeight: '3.4375rem',
    },
    regular: {
      width: '1rem',
      height: '1rem',
      borderRadius: 'var(--ds-corner-radius-2)',
      fontSize: 'var(--ds-font-size-2)',
      lineHeight: '1rem',
    },
    large: {
      width: '1.375rem',
      height: '1.375rem',
      borderRadius: 'var(--ds-corner-radius-3)',
      fontSize: 'var(--ds-font-size-3)',
      lineHeight: '1.375rem',
    },
    xlarge: {
      width: '1.875rem',
      height: '1.875rem',
      borderRadius: 'var(--ds-corner-radius-4)',
      fontSize: 'var(--ds-font-size-4)',
      lineHeight: '1.875rem',
    },
  },
  ellipse: {
    withCamera: {
      width: '4.125rem',
      height: '3.4375rem',
      borderRadius: 'var(--ds-corner-radius-10)',
      fontSize: 'var(--ds-font-size-11)',
      fontWeight: 'bold',
      border: 'var(--ds-borders-1) solid var(--ds-grayscale-80)',
      lineHeight: '3.4375rem',
    },
    regular: {
      width: 'var(--ds-spaces-10)',
      height: 'var(--ds-spaces-8)',
      borderRadius: 'var(--ds-corner-radius-5)',
      fontSize: 'var(--ds-font-size-2)',
      lineHeight: 'var(--ds-spaces-8)',
    },
    large: {
      width: 'var(--ds-spaces-12)',
      height: '1.375rem',
      borderRadius: 'var(--ds-corner-radius-6)',
      fontSize: 'var(--ds-font-size-3)',
      lineHeight: '1.375rem',
    },
    xlarge: {
      width: 'var(--ds-spaces-16)',
      height: 'var(--ds-spaces-14)',
      fontSize: 'var(--ds-font-size-4)',
      borderRadius: 'var(--ds-corner-radius-8)',
      lineHeight: 'var(--ds-spaces-14)',
    },
  },
};
